language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=docs
  - TOXENV=pep8

install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pip install -U -r test_requirements.txt --use-mirrors
script:
  - tox

after_success:
  - pip install python-coveralls --use-mirrors
  - coveralls
